import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createStore} from '../src/storage.mjs';import {createDeliveryService} from '../src/delivery.mjs';import {config} from './fixtures/config.mjs';
const request=(n='1')=>({eventId:'event'+n,teamId:'T12345678',channelId:'C12345678',userId:'U12345678',messageTs:n+'.1',threadTs:n+'.1',alias:'AGENT1',text:'hello'});
async function rig(t,{lost=false,postFails=false,unfinished=false}={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bridge-delivery-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=await createStore({dataDir:dir,secureDirectory:async()=>{}});let marker,now=0,enqueues=0;const delivered=[];const desktop={readChat:async()=>({id:config().routes[0].threadId,name:'Example chat',turns:marker?[{id:'turn1',status:unfinished?'inProgress':'completed',items:[{type:'userMessage',content:[{type:'text',text:marker}]},{type:'agentMessage',phase:'final_answer',text:'hello'}]}]:[]}),listQueue:async()=>({data:[],nextCursor:null}),enqueue:async(id,input)=>{enqueues++;marker=input.marker;if(lost)throw Error('DESKTOP_TIMEOUT');return {queuedSubmission:{id:'queue'}};}};
const postReply=async r=>{if(postFails)throw Error('SLACK_FAILED');delivered.push(r);return {ok:true,ts:'reply'};};const service=()=>createDeliveryService({store,desktop,postReply,config:config(),clock:()=>now,wait:async()=>{now+=500;}});return {store,service,desktop,delivered,count:()=>enqueues};}
test('claims durably and returns final response without duplicate enqueue',async t=>{const r=await rig(t),s=r.service();const a=await s.submit(request());assert.equal(a.status,'TURN_COMPLETED');assert.equal(a.feedback,'sent');assert.ok(r.delivered.some(m=>m.text.includes('hello')));await s.submit(request());assert.equal(r.count(),1);});
test('lost ack survives restart and reconciles existing turn without enqueue',async t=>{const r=await rig(t,{lost:true});const a=await r.service().submit(request());assert.equal(a.status,'UNKNOWN');const b=await r.service().query(a.id);assert.equal(b.status,'TURN_COMPLETED');assert.equal(r.count(),1);});
test('unconfirmed Slack feedback can be explicitly retried without running another task',async t=>{const r=await rig(t,{postFails:true}),s=r.service(),a=await s.submit(request());assert.equal(a.status,'TURN_COMPLETED');assert.equal(a.feedback,'uncertain');await s.retryFeedback(a.id);assert.equal(r.count(),1);});
test('pending previous task blocks a new request',async t=>{const r=await rig(t,{unfinished:true}),s=r.service();const a=await s.submit(request());assert.equal(a.status,'PENDING');await assert.rejects(s.submit(request('2')),/UNRESOLVED/);assert.equal(r.count(),1);});
test('mismatched chat identity and unauthorized users are rejected before submission',async t=>{const r=await rig(t),s=r.service();await assert.rejects(s.submit({...request(),userId:'U99999999'}),/ALLOWLIST/);r.desktop.readChat=async()=>({id:'wrong',name:'Example chat',turns:[]});await assert.rejects(s.submit(request()),/IDENTITY/);assert.equal(r.count(),0);});
test('a later final answer is sent even when pending feedback was already sent',async t=>{const r=await rig(t,{unfinished:true}),s=r.service(),a=await s.submit(request());assert.equal(a.feedback,'sent');r.desktop.readChat=async()=>({id:config().routes[0].threadId,name:'Example chat',turns:[{id:'turn1',status:'completed',items:[{type:'userMessage',content:[{type:'text',text:a.marker}]},{type:'agentMessage',phase:'final_answer',text:'later final'}]}]});await s.query(a.id);await s.retryFeedback(a.id);assert.ok(r.delivered.some(m=>m.text.includes('later final')));assert.equal(r.count(),1);});
test('concurrent feedback retries send one final response',async t=>{const r=await rig(t,{unfinished:true}),s=r.service(),a=await s.submit(request());r.desktop.readChat=async()=>({id:config().routes[0].threadId,name:'Example chat',turns:[{id:'turn1',status:'completed',items:[{type:'userMessage',content:[{type:'text',text:a.marker}]},{type:'agentMessage',phase:'final_answer',text:'concurrent final'}]}]});await Promise.all([s.retryFeedback(a.id),s.retryFeedback(a.id)]);assert.equal(r.delivered.filter(m=>m.text.includes('concurrent final')).length,1);});
