import crypto from 'node:crypto';import {createDeliveryService} from './delivery.mjs';import {createSlackAdapter} from './slack.mjs';import {discoverDesktop} from './desktop/discovery.mjs';import {connectDesktop} from './desktop/client.mjs';
export function createRuntime({store,adapters={}}){
 let running=false,starting=false,desktop,slack,delivery,saved,lastError=null,identity=null;const tests=new Map();
 const update=s=>{if(!s.testNonce||!tests.has(s.testNonce))return;const t=tests.get(s.testNonce);Object.assign(t,{received:true,enqueued:!!s.queuedSubmissionId,answer:s.status==='TURN_COMPLETED'&&s.reply?.trim()===s.testExpected,feedback:s.feedback==='sent',tools:s.toolUsed===false,status:s.status,deliveryId:s.id});t.passed=!!(t.received&&t.enqueued&&t.answer&&t.feedback&&t.tools);};
 const runtime={
 async start(){if(running)return runtime.status();if(starting)throw Error('BRIDGE_STARTING');starting=true;try{saved=await store.readConfig();if(!saved)throw Error('CONFIG_REQUIRED');const {config,secrets}=saved;
 const onDisconnect=()=>{if(running)lastError='DESKTOP_DISCONNECTED';};desktop=adapters.desktop?await adapters.desktop(config,{onDisconnect}):await connectDesktop({paths:await discoverDesktop({overrides:config.desktop}),allowedThreadIds:config.routes.map(r=>r.threadId),onDisconnect});
 const probe=await desktop.probe();if(probe.queueSchema!=='pass')throw Error('DESKTOP_INCOMPATIBLE');if(probe.login!=='pass')throw Error('CODEX_LOGIN_REQUIRED');
 const handle=async r=>{if(!running)return;if(r.kind==='ping'||r.kind==='help'){await slack.postReply({channelId:r.channelId,threadTs:r.threadTs,text:r.kind==='ping'?'Bridge online / Bridge 在线':'Mention bot, then AGENT1: task or AGENT1: status / 提及机器人后发送 AGENT1：任务 或 AGENT1：状态'});return;}
 try{if(r.kind==='status'||r.kind==='feedback'){const records=await store.listDeliveries();const latest=records.filter(x=>x.alias===r.alias&&x.userId===r.userId&&x.channelId===r.channelId).sort((a,b)=>Number(b.messageTs||b.threadTs)-Number(a.messageTs||a.threadTs))[0];if(!latest){await slack.postReply({channelId:r.channelId,threadTs:r.threadTs,text:'No registered task / 尚无登记任务'});return;}let s=await delivery.query(latest.id);if(s.feedback!=='uncertain'||r.kind==='feedback')s=await delivery.retryFeedback(s.id);const warning=s.feedback==='uncertain'?'\nFeedback not confirmed. Explicit retry may repeat the last part: '+s.alias+': retry feedback / 回传未确认，补发可能重复最后一段：'+s.alias+'：补发回复':'';await slack.postReply({channelId:r.channelId,threadTs:r.threadTs,text:s.alias+' · '+s.status+' · feedback / 回传: '+s.feedback+warning});return;}
 if(r.kind!=='task')throw Error('COMMAND_INVALID');const test=[...tests.values()].find(t=>r.text===t.task&&r.alias===t.alias&&!t.received);if(test){r={...r,testNonce:test.nonce,testExpected:test.expected};}
 await delivery.submit(r);
 }catch(e){lastError=/^[A-Z_]+$/.test(e.message)?e.message:'REQUEST_FAILED';await slack.postReply({channelId:r.channelId,threadTs:r.threadTs,text:lastError+' · Not resubmitted / 未重新投递'}).catch(()=>{});}};
 slack=adapters.slack?await adapters.slack({config,secrets,onRequest:handle,onError:code=>lastError=code}):createSlackAdapter({config,secrets,onRequest:handle,onError:code=>lastError=code});
 identity=await slack.verifyIdentity();delivery=createDeliveryService({store,desktop,config,postReply:r=>slack.postReply(r),onUpdate:update});await delivery.reconcile();running=true;try{await slack.start();}catch(e){running=false;throw e;}lastError=null;return runtime.status();
 }catch(e){desktop?.close();await slack?.stop().catch(()=>{});desktop=null;slack=null;throw e;}finally{starting=false;}},
 async stop(){if(starting)throw Error('BRIDGE_STARTING');running=false;desktop?.close();await delivery?.stop();await slack?.stop();desktop=null;slack=null;delivery=null;return runtime.status();},
 status(){return {running,starting,lastError,botId:identity?.botId||null};},
 armTest(alias){if(!running)throw Error('NOT_RUNNING');if(!saved.config.routes.some(r=>r.alias===alias))throw Error('ROUTE_INVALID');const nonce=crypto.randomBytes(12).toString('hex'),expected='BRIDGE_OK_'+nonce,task='Communication test only. Do not call tools, read files or change anything. Reply with exactly: '+expected;const t={nonce,alias,expected,task,received:false,enqueued:false,answer:false,feedback:false,tools:false,passed:false};tests.set(nonce,t);return {nonce,command:alias+': '+task};},
 testStatus(nonce){const t=tests.get(nonce);if(!t)throw Error('TEST_NOT_FOUND');const {expected,task,...safe}=t;return safe;},
 async refreshTest(nonce){const t=tests.get(nonce);if(!t)throw Error('TEST_NOT_FOUND');if(running&&t.deliveryId&&!['CLAIMED','QUEUED'].includes(t.status)){const s=await delivery.query(t.deliveryId);if(['TURN_COMPLETED','FAILED','INTERRUPTED'].includes(s.status)&&s.feedback!=='uncertain')await delivery.retryFeedback(s.id);}return runtime.testStatus(nonce);},
 async retryFeedback(id){if(!running)throw Error('NOT_RUNNING');return delivery.retryFeedback(id);}
 };return runtime;
}
